---
title: "INSERT_TITLE_HERE"
author: "AUTHOR"
navlink: "[NAVTITLE](http://NAVLINK/)"
date: "`r Sys.Date()`"
output: 
  markdowntemplates::default:
    includes: 
      in_header: header.html
---



### Accordéon

<div id="accordion">

<h3>Section 1</h3>
<div>
Voici la partie a1 de l'accordéon.

- tiret 1
- tiret 2
- tiret 3
</div>

<h3>Section 2</h3>
<div>

```{r, echo = F}
knitr::kable(head(mtcars, 3), format = "html")
```
</div>

<h3>Section 3</h3>
<div>

```{r, echo = F, fig.height= 3}
library(ggplot2)
df <- data.frame(
  gp = factor(rep(letters[1:2], each = 4)),
  y = rnorm(8)
)

# The summary data frame ds is used to plot larger red points on top
# of the raw data. Note that we don't need to supply `data` or `mapping`
# in each layer because the defaults from ggplot() are used.
ggplot(df, aes(gp, y)) +
  geom_point()

```

</div>

<h3>Section 4</h3>

Coucou

</div>

<br>

### Onglets

<div id="tabs">
<ul>
  <li><a href="#tabs-1">Section 1</a></li>
  <li><a href="#tabs-2">Section 2</a></li>
  <li><a href="#tabs-3">Section 3</a></li>
  <li><a href="#tabs-4">Section 4</a></li>
</ul>

<div id="tabs-1">

Voici la partie a1 de l'accordéon.

- tiret 1
- tiret 2
- tiret 3


</div>
<div id="tabs-2">


```{r, echo = F}
knitr::kable(head(mtcars, 3), format = "html")
```
</div>


<div id="tabs-3">

```{r, echo = F, fig.height= 3}
library(ggplot2)
df <- data.frame(
  gp = factor(rep(letters[1:2], each = 4)),
  y = rnorm(8)
)

# The summary data frame ds is used to plot larger red points on top
# of the raw data. Note that we don't need to supply `data` or `mapping`
# in each layer because the defaults from ggplot() are used.
ggplot(df, aes(gp, y)) +
  geom_point()

```


</div>


<div id="tabs-4">

Coucou

</div>

</div>


